version: 3

tasks:
  default:
    cmds:
      - task -l

  setup:
    desc: First setup for the project
    cmds:
      - cp .env.dist .env

  execute:
    desc: Execute the project
    cmds:
      - export $(echo $(cat .env | sed 's/#.*//g'| xargs) | envsubst) && go build -o build/exec ./... && build/exec --scope=group --dry-run

  format:
    desc: Execute staticcheck
    cmds:
      - staticcheck ./...
